[tool.poetry]
name = "package"
version = "0.1.0"
description = "ğŸ Boilerplate to kickstart creating a Python package."
readme = "readme.md"
license = "MIT"
authors = ["Sobrino Julian <hello@julito.xyz>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
isort = "^5.4.2"
black = "^20.8b1"
flake8 = "^3.8.3"
mypy = "^0.782"
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
